# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "cloud.google.com/go"
  version = "0.24.0"

[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "12.5.0-beta"

[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = "9.10.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.14.19"

[[constraint]]
  name = "github.com/coredns/coredns"
  version = "1.1.4"

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "3.3.8"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  branch = "master"
  name = "github.com/kubernetes-sigs/federation-v2"

[[constraint]]
  name = "github.com/kubernetes-sigs/kubebuilder"
  version = "0.1.12"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "master"
  name = "google.golang.org/api"

[[constraint]]
  name = "gopkg.in/gcfg.v1"
  version = "1.2.3"

[[constraint]]
  name = "k8s.io/api"
  version="kubernetes-1.10.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version="kubernetes-1.10.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.1"

[prune]
  go-tests = true
  unused-packages = true
