provider: coredns

image:
  name: quay.io/shashidharatd/external-dns
  tag: v0.5.8-dev

sources:
  - crd

extraArgs:
  crd-source-apiversion: multiclusterdns.federation.k8s.io/v1alpha1
  crd-source-kind: DNSEndpoint

extraEnv:
  ETCD_URLS: "http://etcd.federation-system:2379"

txt-owner-id: "baaz"
