apiVersion: federation.k8s.io/v1alpha1
kind: FederatedTypeConfig
metadata:
  name: replicasets.apps
spec:
  target:
    version: v1
    kind: ReplicaSet
  namespaced: true
  comparisonField: Generation
  propagationEnabled: true
  template:
    group: federation.k8s.io
    version: v1alpha1
    kind: FederatedReplicaSet
  placement:
    kind: FederatedReplicaSetPlacement
  override:
    kind: FederatedReplicaSetOverride
  overridePath:
    - spec
    - replicas
