
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.federatedscheduling.k8s.io
  labels:
    api: federation
    apiserver: "true"
spec:
  version: v1alpha1
  group: federatedscheduling.k8s.io
  groupPriorityMinimum: 2000
  priority: 200
  service:
    name: federation
    namespace: federation
  versionPriority: 10
  caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURwekNDQW8rZ0F3SUJBZ0lKQUswTG0rMVkzZitXTUEwR0NTcUdTSWIzRFFFQkN3VUFNR294Q3pBSkJnTlYKQkFZVEFuVnVNUXN3Q1FZRFZRUUlEQUp6ZERFS01BZ0dBMVVFQnd3QmJERUtNQWdHQTFVRUNnd0JiekVMTUFrRwpBMVVFQ3d3Q2IzVXhLVEFuQmdOVkJBTU1JR1psWkdWeVlYUnBiMjR0WTJWeWRHbG1hV05oZEdVdFlYVjBhRzl5CmFYUjVNQjRYRFRFNE1EWXhOREV3TlRBeU9Wb1hEVEU1TURZeE5ERXdOVEF5T1Zvd2FqRUxNQWtHQTFVRUJoTUMKZFc0eEN6QUpCZ05WQkFnTUFuTjBNUW93Q0FZRFZRUUhEQUZzTVFvd0NBWURWUVFLREFGdk1Rc3dDUVlEVlFRTApEQUp2ZFRFcE1DY0dBMVVFQXd3Z1ptVmtaWEpoZEdsdmJpMWpaWEowYVdacFkyRjBaUzFoZFhSb2IzSnBkSGt3CmdnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUMxNVNSZldMcENJVS9ycUJzUFJTNVMKMWhXNFkycmg3YXZQWWhsajlKa2xwZmdrUXk5U2ZkWk42aUE2YWdPSGFDV3B6TmdFRjBkYzc4bjhYbVNDSnNpKwpqeEVxbHdPTld2VTZXN2x6Z0RDOGtHc2pVL0tqRERRR0E5aG52OEN4QWl0VWFNUmhGWFo5dzhZVkluSFV3WUE3CmxvaG1ibWR3aHBuRkxXNFNlRUxLb0ZNY21YNzd0OHhLeTVmZ3lKd3lCVTFQbEE4Y3VhTmlwZGVHazAxMmIyVE0KMlYyVlE3QVhjUmFQWlRqVWxCN3hEUi9DVEQ4M2hIQ0c1eVRNbGZoNDRUcDhCTmRDdUszZ3ZLcVk0U1d3QUFhbApUZFRCUDdoSGJkVzRKek5NeEUxSmlQbzNIUTd5T0hlMG50cFBXZHZVaVJ0K3Q3RU1JK1pNb3lHN1hRUmNMWDBUCkFnTUJBQUdqVURCT01CMEdBMVVkRGdRV0JCUUdRU0NGdDU2aC9ickVJTitROU02eEJaL09iVEFmQmdOVkhTTUUKR0RBV2dCUUdRU0NGdDU2aC9ickVJTitROU02eEJaL09iVEFNQmdOVkhSTUVCVEFEQVFIL01BMEdDU3FHU0liMwpEUUVCQ3dVQUE0SUJBUUNld2xvTXJHU1RHb0diTG5HbGtPM282UmV4aWs5QjZBM3BjU3hUQjYyVnFsMG9NSW5SCjROMnQxckNMQWhlS0NHTElIQjk4cWJsR2o4WEJhSTRLcWNoWDlJZ09UU0JCWmYrQkh4VW1KQWhETGo4akhsOUQKTzFKKzNQTEFtTVBXUVFWbytBL2lVRUhPT2xWOVVjZUN6cUpFWUxxMkxMUFRIYUJhcmFJWWE4NXhIam50Y1pWWQpKOVZ2VStBVW1JdzdwQW5ETXk5ODlRMG9QMm5sTmtsMk93SC9QTWZsVlBhc3lkRGtIWkM3OFVqbTd3S1A0LzVhClJzaVFIVEt3UXg5d0NmeDN1aU5ZbG9YSkdrMXBDVG90N2xiYzl2ME8xYUxKOFVnYTZOQnBKRFI3dzhncHFoRngKWXhUM0xsRmhKWXhQQVdzOWFGOVJ1UTI3ZzdySFBZWkpDMkd6Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
---
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.federation.k8s.io
  labels:
    api: federation
    apiserver: "true"
spec:
  version: v1alpha1
  group: federation.k8s.io
  groupPriorityMinimum: 2000
  priority: 200
  service:
    name: federation
    namespace: federation
  versionPriority: 10
  caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURwekNDQW8rZ0F3SUJBZ0lKQUswTG0rMVkzZitXTUEwR0NTcUdTSWIzRFFFQkN3VUFNR294Q3pBSkJnTlYKQkFZVEFuVnVNUXN3Q1FZRFZRUUlEQUp6ZERFS01BZ0dBMVVFQnd3QmJERUtNQWdHQTFVRUNnd0JiekVMTUFrRwpBMVVFQ3d3Q2IzVXhLVEFuQmdOVkJBTU1JR1psWkdWeVlYUnBiMjR0WTJWeWRHbG1hV05oZEdVdFlYVjBhRzl5CmFYUjVNQjRYRFRFNE1EWXhOREV3TlRBeU9Wb1hEVEU1TURZeE5ERXdOVEF5T1Zvd2FqRUxNQWtHQTFVRUJoTUMKZFc0eEN6QUpCZ05WQkFnTUFuTjBNUW93Q0FZRFZRUUhEQUZzTVFvd0NBWURWUVFLREFGdk1Rc3dDUVlEVlFRTApEQUp2ZFRFcE1DY0dBMVVFQXd3Z1ptVmtaWEpoZEdsdmJpMWpaWEowYVdacFkyRjBaUzFoZFhSb2IzSnBkSGt3CmdnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUMxNVNSZldMcENJVS9ycUJzUFJTNVMKMWhXNFkycmg3YXZQWWhsajlKa2xwZmdrUXk5U2ZkWk42aUE2YWdPSGFDV3B6TmdFRjBkYzc4bjhYbVNDSnNpKwpqeEVxbHdPTld2VTZXN2x6Z0RDOGtHc2pVL0tqRERRR0E5aG52OEN4QWl0VWFNUmhGWFo5dzhZVkluSFV3WUE3CmxvaG1ibWR3aHBuRkxXNFNlRUxLb0ZNY21YNzd0OHhLeTVmZ3lKd3lCVTFQbEE4Y3VhTmlwZGVHazAxMmIyVE0KMlYyVlE3QVhjUmFQWlRqVWxCN3hEUi9DVEQ4M2hIQ0c1eVRNbGZoNDRUcDhCTmRDdUszZ3ZLcVk0U1d3QUFhbApUZFRCUDdoSGJkVzRKek5NeEUxSmlQbzNIUTd5T0hlMG50cFBXZHZVaVJ0K3Q3RU1JK1pNb3lHN1hRUmNMWDBUCkFnTUJBQUdqVURCT01CMEdBMVVkRGdRV0JCUUdRU0NGdDU2aC9ickVJTitROU02eEJaL09iVEFmQmdOVkhTTUUKR0RBV2dCUUdRU0NGdDU2aC9ickVJTitROU02eEJaL09iVEFNQmdOVkhSTUVCVEFEQVFIL01BMEdDU3FHU0liMwpEUUVCQ3dVQUE0SUJBUUNld2xvTXJHU1RHb0diTG5HbGtPM282UmV4aWs5QjZBM3BjU3hUQjYyVnFsMG9NSW5SCjROMnQxckNMQWhlS0NHTElIQjk4cWJsR2o4WEJhSTRLcWNoWDlJZ09UU0JCWmYrQkh4VW1KQWhETGo4akhsOUQKTzFKKzNQTEFtTVBXUVFWbytBL2lVRUhPT2xWOVVjZUN6cUpFWUxxMkxMUFRIYUJhcmFJWWE4NXhIam50Y1pWWQpKOVZ2VStBVW1JdzdwQW5ETXk5ODlRMG9QMm5sTmtsMk93SC9QTWZsVlBhc3lkRGtIWkM3OFVqbTd3S1A0LzVhClJzaVFIVEt3UXg5d0NmeDN1aU5ZbG9YSkdrMXBDVG90N2xiYzl2ME8xYUxKOFVnYTZOQnBKRFI3dzhncHFoRngKWXhUM0xsRmhKWXhQQVdzOWFGOVJ1UTI3ZzdySFBZWkpDMkd6Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
---
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.multiclusterdns.k8s.io
  labels:
    api: federation
    apiserver: "true"
spec:
  version: v1alpha1
  group: multiclusterdns.k8s.io
  groupPriorityMinimum: 2000
  priority: 200
  service:
    name: federation
    namespace: federation
  versionPriority: 10
  caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURwekNDQW8rZ0F3SUJBZ0lKQUswTG0rMVkzZitXTUEwR0NTcUdTSWIzRFFFQkN3VUFNR294Q3pBSkJnTlYKQkFZVEFuVnVNUXN3Q1FZRFZRUUlEQUp6ZERFS01BZ0dBMVVFQnd3QmJERUtNQWdHQTFVRUNnd0JiekVMTUFrRwpBMVVFQ3d3Q2IzVXhLVEFuQmdOVkJBTU1JR1psWkdWeVlYUnBiMjR0WTJWeWRHbG1hV05oZEdVdFlYVjBhRzl5CmFYUjVNQjRYRFRFNE1EWXhOREV3TlRBeU9Wb1hEVEU1TURZeE5ERXdOVEF5T1Zvd2FqRUxNQWtHQTFVRUJoTUMKZFc0eEN6QUpCZ05WQkFnTUFuTjBNUW93Q0FZRFZRUUhEQUZzTVFvd0NBWURWUVFLREFGdk1Rc3dDUVlEVlFRTApEQUp2ZFRFcE1DY0dBMVVFQXd3Z1ptVmtaWEpoZEdsdmJpMWpaWEowYVdacFkyRjBaUzFoZFhSb2IzSnBkSGt3CmdnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUMxNVNSZldMcENJVS9ycUJzUFJTNVMKMWhXNFkycmg3YXZQWWhsajlKa2xwZmdrUXk5U2ZkWk42aUE2YWdPSGFDV3B6TmdFRjBkYzc4bjhYbVNDSnNpKwpqeEVxbHdPTld2VTZXN2x6Z0RDOGtHc2pVL0tqRERRR0E5aG52OEN4QWl0VWFNUmhGWFo5dzhZVkluSFV3WUE3CmxvaG1ibWR3aHBuRkxXNFNlRUxLb0ZNY21YNzd0OHhLeTVmZ3lKd3lCVTFQbEE4Y3VhTmlwZGVHazAxMmIyVE0KMlYyVlE3QVhjUmFQWlRqVWxCN3hEUi9DVEQ4M2hIQ0c1eVRNbGZoNDRUcDhCTmRDdUszZ3ZLcVk0U1d3QUFhbApUZFRCUDdoSGJkVzRKek5NeEUxSmlQbzNIUTd5T0hlMG50cFBXZHZVaVJ0K3Q3RU1JK1pNb3lHN1hRUmNMWDBUCkFnTUJBQUdqVURCT01CMEdBMVVkRGdRV0JCUUdRU0NGdDU2aC9ickVJTitROU02eEJaL09iVEFmQmdOVkhTTUUKR0RBV2dCUUdRU0NGdDU2aC9ickVJTitROU02eEJaL09iVEFNQmdOVkhSTUVCVEFEQVFIL01BMEdDU3FHU0liMwpEUUVCQ3dVQUE0SUJBUUNld2xvTXJHU1RHb0diTG5HbGtPM282UmV4aWs5QjZBM3BjU3hUQjYyVnFsMG9NSW5SCjROMnQxckNMQWhlS0NHTElIQjk4cWJsR2o4WEJhSTRLcWNoWDlJZ09UU0JCWmYrQkh4VW1KQWhETGo4akhsOUQKTzFKKzNQTEFtTVBXUVFWbytBL2lVRUhPT2xWOVVjZUN6cUpFWUxxMkxMUFRIYUJhcmFJWWE4NXhIam50Y1pWWQpKOVZ2VStBVW1JdzdwQW5ETXk5ODlRMG9QMm5sTmtsMk93SC9QTWZsVlBhc3lkRGtIWkM3OFVqbTd3S1A0LzVhClJzaVFIVEt3UXg5d0NmeDN1aU5ZbG9YSkdrMXBDVG90N2xiYzl2ME8xYUxKOFVnYTZOQnBKRFI3dzhncHFoRngKWXhUM0xsRmhKWXhQQVdzOWFGOVJ1UTI3ZzdySFBZWkpDMkd6Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
---
apiVersion: v1
kind: Service
metadata:
  name: federation
  namespace: federation
  labels:
    api: federation
    apiserver: "true"
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    api: federation
    apiserver: "true"
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: federation
  namespace: federation
  labels:
    api: federation
    apiserver: "true"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        api: federation
        apiserver: "true"
    spec:
      containers:
      - name: apiserver
        image: shashidharatd/federation-v2:test
        volumeMounts:
        - name: apiserver-certs
          mountPath: /apiserver.local.config/certificates
          readOnly: true
        command:
        - "./apiserver"
        args:
        - "--etcd-servers=http://etcd-svc:2379"
        - "--tls-cert-file=/apiserver.local.config/certificates/tls.crt"
        - "--tls-private-key-file=/apiserver.local.config/certificates/tls.key"
        - "--audit-log-path=-"
        - "--audit-log-maxage=0"
        - "--audit-log-maxbackup=0"
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
      - name: controller
        image: shashidharatd/federation-v2:test
        command:
        - "./controller-manager"
        args:
        - "-logtostderr"
        - "-v=4"
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
      volumes:
      - name: apiserver-certs
        secret:
          secretName: federation
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: etcd
  namespace: federation
spec:
  serviceName: "etcd"
  replicas: 1
  template:
    metadata:
      labels:
        app: etcd
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        env:
        - name: ETCD_DATA_DIR
          value: /etcd-data-dir
        command:
        - /usr/local/bin/etcd
        - --listen-client-urls
        - http://0.0.0.0:2379
        - --advertise-client-urls
        - http://localhost:2379
        ports:
        - containerPort: 2379
        volumeMounts:
        - name: etcd-data-dir
          mountPath: /etcd-data-dir
        readinessProbe:
          httpGet:
            port: 2379
            path: /health
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            port: 2379
            path: /health
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
  volumeClaimTemplates:
  - metadata:
     name: etcd-data-dir
     annotations:
        volume.beta.kubernetes.io/storage-class: standard
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
         storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: etcd-svc
  namespace: federation
  labels:
    app: etcd
spec:
  ports:
  - port: 2379
    name: etcd
    targetPort: 2379
  selector:
    app: etcd
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: federation
  namespace: federation
  labels:
    api: federation
    apiserver: "true"
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURTVENDQWpFQ0NRQ1FCR3ZiV0FPZkdUQU5CZ2txaGtpRzl3MEJBUXNGQURCcU1Rc3dDUVlEVlFRR0V3SjEKYmpFTE1Ba0dBMVVFQ0F3Q2MzUXhDakFJQmdOVkJBY01BV3d4Q2pBSUJnTlZCQW9NQVc4eEN6QUpCZ05WQkFzTQpBbTkxTVNrd0p3WURWUVFERENCbVpXUmxjbUYwYVc5dUxXTmxjblJwWm1sallYUmxMV0YxZEdodmNtbDBlVEFlCkZ3MHhPREEyTVRReE1EVXdNamxhRncweE9UQTJNVFF4TURVd01qbGFNR014Q3pBSkJnTlZCQVlUQW5WdU1Rc3cKQ1FZRFZRUUlEQUp6ZERFS01BZ0dBMVVFQnd3QmJERUtNQWdHQTFVRUNnd0JiekVMTUFrR0ExVUVDd3dDYjNVeApJakFnQmdOVkJBTU1HV1psWkdWeVlYUnBiMjR1Wm1Wa1pYSmhkR2x2Ymk1emRtTXdnZ0VpTUEwR0NTcUdTSWIzCkRRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRGZxVDBmazZZMXJvdWtTTEF3dWhZUnpiQU5xVDluWnlHRlNoQTMKc0R0WjRqdmw3WGlJS1lXaHhEWFZUbzhvOGlaV1JMS3J4MkdPZTRmL1FFdzNNdEVLZnV4QnlvMnpsTGVybmo4Swo5MTdVc0xRUDd0d0lFV1V4WmkzRU9yWEcwNXhhdXlnbnNtajZDZXp6RnlZMStoWSs1T1ZCUkFmZEVvemZ0RW1SCkVONlVOVVBSdWJUbHd0Wm1mQlhsTE9ZQmxZQnRTT0JCYyt0WXFmdjhTNEFzM014eW9maVc5T3ZUSDRWVEVlVjcKYmp2TDJWZXVRR3pFQlhYY2RZM3FxQThPZkVEWDBtaGxhcGVpOERralpYdHBaNStyQ2JESEFvSXdQNDIvcnRiWAo1b3c2MGVxd2hwd0RmREJKZmh3WElMUjRyckhHY20zWjlQaWVGK0ZjY0tVeVpRalhBZ01CQUFFd0RRWUpLb1pJCmh2Y05BUUVMQlFBRGdnRUJBRjdiZDFjZzI0ZmgzTHAyWXhyZFVTRTEvR0hxWjMyZ29UUk04aXN1YXJ1RWFua1EKTjlyVTc1QVo0WDRzdHN6czJoK2xFdVkrTnRnYVpRRitRZm9KRU15VTI2YUp3bXJ3ZkdUMlhlZnF1eHcwekt1OQo5M2F1a2ZkL2YwaWRtMm91c3pybjJWRFZKbGExRGRnNnVlVWNRMEVkV0ZBNGowTjVkME5oOVp3ZUNFeXUzbjZJCnhFUmx1a04wQWpTY3RvTUJXWGlVa0UxUUF4Y2YvejdhQmd6SzRwV2VZWk9qTGpmVE1nTmVENzlzRXpSVDdVZkQKdnpCMm9wakJLeWxjdUpRYWJQcnAvc2kvNE5kaXdWcysrQnUvS050UmhjY3hua1BsWlhUdTgzR04vT0tDUmoyNQpUdW5ySmh0M1I3RDVRU0hNWFNSYkVCeWRpb1ZtNnI2Rkp3NVg2QzQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRRGZxVDBmazZZMXJvdWsKU0xBd3VoWVJ6YkFOcVQ5blp5R0ZTaEEzc0R0WjRqdmw3WGlJS1lXaHhEWFZUbzhvOGlaV1JMS3J4MkdPZTRmLwpRRXczTXRFS2Z1eEJ5bzJ6bExlcm5qOEs5MTdVc0xRUDd0d0lFV1V4WmkzRU9yWEcwNXhhdXlnbnNtajZDZXp6CkZ5WTEraFkrNU9WQlJBZmRFb3pmdEVtUkVONlVOVVBSdWJUbHd0Wm1mQlhsTE9ZQmxZQnRTT0JCYyt0WXFmdjgKUzRBczNNeHlvZmlXOU92VEg0VlRFZVY3Ymp2TDJWZXVRR3pFQlhYY2RZM3FxQThPZkVEWDBtaGxhcGVpOERragpaWHRwWjUrckNiREhBb0l3UDQyL3J0Ylg1b3c2MGVxd2hwd0RmREJKZmh3WElMUjRyckhHY20zWjlQaWVGK0ZjCmNLVXlaUWpYQWdNQkFBRUNnZ0VBYXpLZlJDb3RTSjl1K0grS1N1QjF3WFMzUStUeHFhckpheXdUVjgyVXRNRDAKK24vMS9EVUNnb1ViVkRCQjkxc1FPdHJVVS9iTThGQ08zeTAvR2xtMXpYVUY0WWFtb2dMT2dXZm9TV1pFd21ZcQo5MVFCaTdCaXN1bUpWL3JYc3dNcmRtVXJtdE1zODJLY2VlcUhldWx4amhXQk4rWFdhd1FBRnh3L0FsTjJpc3VUClNvWmNRei9PVDBmS082ank2SUJRNFliVXlHQVc4S1BITDFidEVRYWdUWi9JbWFBNUsxZ2JETDZ6SElwTXpZRUIKTzUwZFRRc2N5a2QraUN6eDZmcDQwRGxYYWtCcFZSRkpyeCtRb1phTlVhNWpGSndZYXlmaHhNOFB4WW1ac1hQQgo0K09FNEpLYTNlRjIwaUJUcW1PelRTU014bXVhVGdodERGMXg5WXlQUVFLQmdRRDJpQzY0L2lsMXMzU3l2bE1aCitXS1FrU25IUE0rMnM4UmJuUy8vT1ppNFp0Z2wvQ3NKL3hBT29CbzBQeDJ0Y0haT2VEUHgyaERLek5uVEhtTkIKLzF5RlFTKzFEVllWSzB5azdBUzU3aG1YU0FFdlF3aFhNQWZweVM1UEYwSDRUdlpnbXRhMDRWa1psZUp2Q251WgpPZ20rSDB2UjNxV0lJaVdCY0pWT2ZvdFBvUUtCZ1FEb1FES2JaVHNpZFAxN0dkbWEyLzNSK1p4Tng1VWtVRTl3CmdXc0hPTnB0VWJrUWZoUGFjcTZNZGZtVGZvZTRnSlhIdEZhbmNidEc5WmRXbnVUTklnKzZVK0NtMkdNY21zYmEKcjZWSWVCTnZXQkxvUTBQREtOV2xObDN2MlFRN2pPRy9OWmxuRURZVk1KdzdqQ3ErYlRHNHBldmZjcDJBbjhqWgpoNEtFYUdqbGR3S0JnUURJVWJmRlVhQldwMDczdm5hLzhFZ0t1Q2wrWHdkWXFaR3Y3M1dFcVVSUzhoNUlIekxKCm1KdHZodUJEKzlVZGpQaFVvbzl5d1lKTGgxQ25uMVYvMXdOU3M3a1VJSllGOVh6OXRWblJ5b3E0eGlWUVJlT04KRk5ZWlBRT0grSm4rTGdzOFRCU1NQVm1zMUlGOVFNTlZxamNvYVQydWRuK0NzbHhQWlMrczdGNCtnUUtCZ0E4cgp5bUorUFZ1bDJyMEUxa01ZWmI4bW1BQTRybFJkN3FLQndiVUtFTEtkYVFKYnlmNDJDWkxoVGZsRmhhWVd1RElBClpMeXhZRE5sYllwWi9NWXRtR3RxZVQxTTIwU09FN2xMU2ZldTZFNFlxYnVFVVZQWlFnTjF4ck1aTVA2VzJGUSsKTXhRWmFmNytXdVpFNUxIbHZoNjZyK3E3dVBBaS8rSzl5RmZQM2pKSEFvR0JBS3NRdHB3S01Sc2V6cUx0eExEdApIa0FTc2ZxVCs0ak9zSmt5RzJRK2R3bW5DTzduOGlTQjRxUm5OK2wyc0ZPVGJycEdXY3RoVmF0WndGRFFJRVdWCkVjb0VxWGkzTjgzUU00Q09OdHprNkx3S1hBSjFwcjM3NVJwbTNZOEZvOWlWbEpZaXoxd2gvbVdTWWJjQ3FIY2EKUkFvUjI0QnVudnN0ZjNOMHBPRXpBbUk1Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
